### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by daashkins** [daashkins/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by MylnikovaDaria** [comment]
— Hello! I’m a highly motivated future front-end developer without any commercial experience. Yeah, it’s true. I’m looking for a company willing to offer me a placement among their developers. In return, I would offer my full commitment, and be a pleasant and friendly addition to your team. I’m therefore currently looking for a job or n internship as a front-end developer. So I’m ready for new challenges.

**Comment by daashkins** [comment]
Please transform this into HTML form

**Comment by MylnikovaDaria** [comment]
```
<h2>Résumé</h2>
<p>&mdash; Hello! I’m a highly motivated future front-end developer without any commercial experience. Yeah, it’s true. I’m looking for a company willing to offer me a placement among their developers. In return, I would offer my full commitment, and be a pleasant and friendly addition to your team. I’m therefore currently looking for a job or n internship as a front-end developer. So I’m ready for new challenges.</p>
```
