### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by daashkins** [daashkins/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by MylnikovaDaria** [comment]
Now
21 December 2019  - present
Unemployed. 
OMG. But living in Amsterdam, Netherlands and trying to refresh my JS knowlenge.

Back then 
10th June 2019 - 18 December 2019
Senior Accountant at Astound Commerce
Great come back to my job after looooooonnnngggg maternity leave.
—  Bookkeeping and preparing reports to authorities. Dealing with a lot of money, taxes etc.
—  Onboarding new empoyees
—  Preparing technical documentation for 1C improvements.
— And all responsibilities that I had before maternity leave

February 2019 - June 2019
Decided to get acquainted with Javascript.
— going to lectures
— doing  a lot of homework
— preparing pet projects 
HTML, CSS, Javascript, SASS, SCSS, GIT, Bootstrap, Material UI, React, Emmet, BEM, Photoshop

October 2018 - December 2018
Take a decision to learn Frontend. It’s never too late to change your specialisation, isn’t it? 
— lectures
— homework’s
— a lot of html and css
— sleepless nights again
— blowing mind

WAY BACK THEN
6th March 2017 
My child  Pasha was born and our life goes like  this
sleepless nights
dipers
breastfeeding
mimimi
new achievements	
playing
long, long walks trying not to awake child

15 th June 2016
Get married with Alexander and afterwards we found out that we got best gift ever.

2014 -2016 
Senior Accountant at Astound Commerce
— Control of the correctness of company contracts for accounting purposes;
— Prepares asset, liability, and capital account entries by compiling and analyzing account information;
— Documents financial transactions by entering account information;
— Payroll
— Summarizes current financial status by collecting information; preparing balance sheet, profit and loss statement, and other reports;
— Maintains accounting controls by preparing and recommending policies and procedures;
— Communication with external auditors.

Some time in 2013 
Met my future husband at work.

2013 - 2014
— Prepares asset, liability, and capital account entries by compiling and analyzing account information;
— Documents financial transactions by entering account information;
— Accountant at Astound Commerce
— Prepares payments by verifying documentation;
— Inventory of assets
— Payroll

June 2012 -December 2012 
PE Accountant at Astound Commerce
— Coordination of opening and closing the PEs;
— Quarterly preparation of tax reports and bookkeeping;
— Organization and tracking the completeness of PE documents required;
— Supporting new presentations and instructions for the PEs;


February 2012 
Accountant Assistant at Astound Commerce
So I got my first real job. And my task were:
— coping	documents
— printing documents
— sorting documents 
Really hard tasks, but I leaned fast and became a level 80 Accountant Assistant. And obviously get promoted. Yehaaaa.

September 2008 
Found out that I was accepted to university in Kyiv. Fastly packed my stuff and began my grown up life. Started to prepare food by myself and missed Mom’s food, especially cakes. So be careful what you wish for. 

31 May 2008 
Graduated from school. Thanks God! The real life is coming.

14th January 1997
My sister was born, so I’ve started to have more fun.

30 th October 1990 
Born in Lugansk, Ukraine

**Comment by daashkins** [comment]
Please transform this into HTML form

**Comment by MylnikovaDaria** [comment]
<h3>Experience</h3>
                  <h6>Now</h6>
                  <ul class="timeline">
                    <li>
                      <p><em>21<sup>th</sup> December 2019 - present</em></p>
                      <p><strong>Unemployed</strong></p>
                      <p>OMG. But living in <strong><a href="https://www.google.com/maps/place/%D0%90%D0%BC%D1%81%D1%82%D0%B5%D1%80%D0%B4%D0%B0%D0%BC/@52.3547497,4.8337494,12z/data=!3m1!4b1!4m5!3m4!1s0x47c63fb5949a7755:0x6600fd4cb7c0af8d!8m2!3d52.3666969!4d4.8945398" rel="external">Amsterdam</a></strong>, Netherlands and trying to refresh my JS knowlenge.</p>
                    </li>
                  </ul>
                  <h6>Back then</h6>
                  <ul class="timeline">
                    <li>
                      <p><em>10<sup>th</sup> June 2019 &ndash; 18<sup>th</sup> December 2019</em></p>
                      <p><strong>Senior Accountant</strong> at <strong><a href="https://astoundcommerce.com/" rel="external">Astound Commerce</a></strong></p>
                      <p>Great come back to my job after looooooonnnngggg maternity leave.</p>
                      <ul>
                        <li>all responsibilities that I had before maternity leave.</li>
                        <li>bookkeeping and preparing reports to authorities. Dealing with a lot of money, taxes etc.</li>
                        <li>onboarding new employees.</li>
                        <li>preparing technical documentation for 1C improvements.</li>
                      </ul>
                    </li>
                      <li>
                          <p><em>February 2019 &ndash; June 2019</em></p>
                          <p>Decided to get acquainted with <strong>Javascript</strong>.</p>
                         <ul>
                            <li>going to lectures</li>
                            <li>doing a lot of homework</li>
                            <li>preparing pet projects </li>
                            <li class="details">
                              <input type="checkbox" id="project-3">
                              <label for="project-3" class="summary">learning a lot of new information</label>
                              <div class="labels">
                                <p class="label">HTML</p>
                                <p class="label">CSS</p>
                                <p class="label">JS</p>
                                <p class="label">SASS</p>
                                <p class="label">GIT</p>
                                <p class="label">HTML</p>
                                <p class="label">Bootstrap</p>
                                <p class="label">React</p>
                              </div>
                            </li>
                          </ul>
                        </li>
                        <li>
                          <p><em>October 2018 &ndash; December 2018</em></p>
                          <p>Take a decision to learn <strong>Frontend</strong>. It’s never too late to change your specialisation, isn’t it? </p>
                          <ul>
                            <li>lectures</li>
                            <li>homework’s</li>
                            <li> a lot of html and css code</li>
                            <li>sleepless nights again</li>
                            <li> blowing mind</li>
                          </ul>
                        </li>
                    </ul>
                    <h6>Way back then</h6>
                    <ul class="timeline">
                      <li>
                        <p><em>6<sup>th</sup> March 2017 </em></p>
                        <p>My child  Pasha was born and our life goes like  this</p>
                        <div id="piechart" style="margin-left: -30px; margin-bottom: -30px;"> </div>
                      </li>
                      <li class="details">
                        <p><em> 2014 &ndash; 2016 </em></p>
                        <input type="checkbox" id="project-3">
                        <label for="project-3" class="summary"> <strong>Senior Accountant</strong> at <strong><a href="https://astoundcommerce.com/" rel="external">Astound Commerce</a></strong></label>
                        <div class="labels">
                          <ul> 
                            <li>control of the correctness of company contracts for accounting purposes</li>
                            <li>prepares asset, liability, and capital account entries by compiling and analyzing account information</li>
                            <li>documents financial transactions by entering account information</li>
                            <li>payroll</li>
                            <li>summarizes current financial status by collecting information; preparing balance sheet, profit and loss statement, and other reports</li>
                            <li>maintains accounting controls by preparing and recommending policies and procedures</li>
                            <li>Communication with external auditors</li>
                          </ul>
                        </div>
                      </li>
                      <li>
                        <p><em>Some time in 2013 </em></p>
                        <p>Met my future husband at work.</p>
                      </li>
                      <li class="details">
                        <p><em> 2013 &ndash; 2014 </em></p>
                        <input type="checkbox" id="project-3">
                        <label for="project-3" class="summary"><strong>Accountant</strong> at <strong><a href="https://astoundcommerce.com/" rel="external">Astound Commerce</a></strong></label>
                        <div class="labels">
                          <ul> 
                            <li>prepares asset, liability, and capital account entries by compiling and analyzing account information</li>
                            <li>documents financial transactions by entering account information</li>
                            <li>prepares payments by verifying documentation</li>
                            <li>payroll</li>
                            <li>inventory of assets</li>
                          </ul>
                        </div>
                      </li>
                      <li class="details">
                        <p><em> 2012 &ndash; 2013 </em></p>
                        <input type="checkbox" id="project-3">
                        <label for="project-3" class="summary"><strong>PE Accountant </strong> at <strong><a href="https://astoundcommerce.com/" rel="external">Astound Commerce</a></strong></label>
                        <div class="labels">
                          <ul> 
                            <li>coordination of opening and closing the PEs</li>
                            <li>quarterly preparation of tax reports and bookkeeping</li>
                            <li>organization and tracking the completeness of PE documents required</li>
                            <li>supporting new presentations and instructions for the PEs</li>
                          </ul>
                        </div>
                     </li>
                     <li class="details">
                      <p><em> February  2013</em></p>
                      <p><strong>Accountant Assistant </strong> at <strong><a href="https://astoundcommerce.com/" rel="external">Astound Commerce</a></strong></p>
                      <input type="checkbox" id="project-3">
                      <label for="project-3" class="summary">So I got my first real job. My tasks were really hard, but I leaned fast and became a level 80 Accountant Assistant.
                      Obviously I got promoted. Yehaaaa.</label>
                      <div class="labels">
                        <ul> 
                          <li>coping documents</li>
                          <li>printing documents</li>
                          <li>sorting documents </li>
                        </ul>
                      </div>
                    </li>
                    <li>
  	                  <p><em>September 2008 </em></p>
                      <p>Found out that I was accepted to university in <strong><a href="https://www.google.com/maps/place/Kyiv,+Ukraine,+02000/@50.4021698,30.3922653,11z/data=!3m1!4b1!4m5!3m4!1s0x40d4cf4ee15a4505:0x764931d2170146fe!8m2!3d50.4501!4d30.5234" 
                        rel="external">Kyiv</a></strong>. Fastly packed my stuff and began my 		grown up life. Started to prepare food by myself and missed Mom’s food, especially cakes. So be careful what you wish for. </p>
	                  </li>
                    <li>
                      <p><em>31<sup>st</sup> May 2008 </em></p>
                      <p>Graduated from school. Thanks God! The real life is coming.</p>
                    </li>
                    <li>
                      <p><em>30<sup>th</sup> October 1990</em></p>
                      <p>Born in <strong><a href="https://www.google.com/maps/place/Luhansk,+Luhansk+Oblast,+Ukraine,+91000/@48.5802058,39.2165421,11z/data=!3m1!4b1!4m5!3m4!1s0x411fc564844c6285:0xf8e02e7e879e7164!8m2!3d48.574041!4d39.307815" 
                        rel="external">Lugansk, Ukraine</a></strong></p>
	                  </li>
                  </ul>
