### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by daashkins** [daashkins/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by MylnikovaDaria** [comment]
Education
February 2019 - June 2019
Front-end Course
Beetroot Academy 

October 2018 - December 2018
HTML, CSS Course
Infopulse 

June 2015
Diploma in International Financial Reporting

2010 -2011
French course
Alliance Française Kyiv

2008 -2013
Faculty of Accounting and Audit 
Kyiv National Economic University named after Vadym Hetman

**Comment by MylnikovaDaria** [comment]
LANGUAGES
English Українська Русский Francais

SKILLS
HTML CSS JS REACT WEBPACK GULP  NPM BOOTSTRAP SEMANTIC UI LESS SASS  MICROSOFT OFFICE PHOTOSHOP ILLUSTRATOR MATERIAL UI

CHARACTER
FUNNY RESPONSIBLE CONSISTENT CHALLENGING ENTHUSIASTIC CONFIDENT 

LIKES
HUMOUR MOVIES SERIES MUSIC YOGA BOOKS HAVING FUN  TRAVELLING COOKING EATING SEA and BEACHES Word “naïve” SUPERBOWL COMMERCIALS OSCAR

DISLIKES
SPIDERS OWN BAD HABITS POLITICS VODKA ARROGANCE VIOLENCE MILK 

WANTS
TO BE FIT AND HEALTHY VISIT NY AGAIN LEARN HOW TO SWIM LEARN FRENCH FLUENTLY READ A LOT HAVE MY OWN BUSINESS

**Comment by daashkins** [comment]
Please transform this into HTML form.

**Comment by MylnikovaDaria** [comment]
<section>
                  <h3>Languages</h3>
                  <p class="tags small"><span class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА</span><span class="language" lang="ru"
                  >&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span><span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
                </section>
                <section>
                  <h3>Skills</h3>
                  <p class="tags small">HTML CSS JS REACT WEBPACK GULP  NPM BOOTSTRAP  <span class="nowrap">SEMANTIC UI</span> LESS SASS  <span class="nowrap">MICROSOFT OFFICE</span> PHOTOSHOP ILLUSTRATOR WINDOWS MACOS <span class="nowrap">MATERIAL UI</span> </p>
                </section>
                <section>
                  <h3>Character</h3>
                  <p class="tags small">FUNNY RESPONSIBLE CONSISTENT CHALLENGING ENTHUSIASTIC CONFIDENT </p>
                </section>
                <section>
                  <h3>Likes&#x1f603;</h3>
                  <p class="tags small">HUMOUR 
                  HUMOUR  <span class="nowrap">HAVING FUN </span> TRAVELLING COOKING EATING  <span class="nowrap">SEA AND BEACHES </span> <span class="nowrap">Word “naïve”</span> ​<span class="nowrap">SUPERBOWL COMMERCIALS</span>OSCAR COSMETICS FASHON BIRDS NATURE</p>
                </section>
                <section>
                  <h3>Dislikes&#x1f61e;</h3>
                  <p class="tags small">SPIDERS<span class="nowrap">OWN BAD HABITS</span> POLITICS VODKA ARROGANCE ENVY VIOLENCE MILK </p>
                </section>
                <section>
                  <h3>Wants&#x1f97a;</h3>
                  <p class="tags small bulleted"><span class="tag">TO BE FIT AND HEALTHY</span><span class="tag">VISIT NY AGAIN</span><span class="tag">LEARN HOW TO SWIM</span><span class="tag">SPEAK FRENCH FLUENTLY</span><span class="tag">TO BE BRAVE</span><span class="tag">HAVE MY OWN BUSINESS </span><span class="tag">READ A LOT </span></p>
                </section>
                <section>
                  <h3>Education</h3>
                  <ul class="timeline">
                    <li>
                      <div><em>February 2019 &ndash; June 2019</em></div>
                      <div><strong>Front-end Course</strong> at <a href="https://beetroot.academy/en/" rel="external"><strong>Beetroot Academy </strong></a></div>
                    </li>
                    <li>
                      <div><em>October 2018  &ndash; December 2018</em></div>
                      <div><strong>HTML, CSS Course </strong> at <a href="http://infopulse-school.com.ua/" rel="external"><strong>Infopulse </strong></a></div>
                    </li>
                    <li>
                      <div><em>June 2015</em></div>
                      <div><strong>Diploma in International Financial Reporting</strong> </div>
                    </li>
                    <li>
                      <div><em>1<sup>st</sup> September 1993 &ndash; 21<sup>st</sup> June 2003</em></div>
                      <div><strong>Certificate of graduation</strong> at <strong>№20 Middle School of General Education</strong></div>
                    </li>
                    <li>
                      <div><em>2010 &ndash; 2011</em></div>
                      <div><strong>French course</strong> at <strong>Alliance Française Kyiv</strong></div>
                    </li>
                    <li>
                      <div><em>2008 &ndash; 2013</em></div>
                      <div><strong>Faculty of Accounting and Audit </strong> at <strong>Kyiv National Economic 
                        University named after Vadym Hetman</strong></div>
                    </li>
                    </ul>
                  </section>
