### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by daashkins** [daashkins/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by MylnikovaDaria** [comment]
<h3>Languages</h3>
                <p class="tags small"><span class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА
                  </span></span><span class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ </span></span> <span
                  class="language" lang="en">&#x1f1fa;&#x1f1f8; <span>ENGLISH </span></span></p>
              </section>
              <section style="padding: 1.5em 0">
                <h3>Skills&#129504;</h3>
                <p class="tags small">HTML CSS JS REACT WEBPACK GULP NPM BOOTSTRAP  <span class="nowrap">SEMANTIC
                  UI</span> LESS SASS <span class="nowrap">MICROSOFT OFFICE</span> PHOTOSHOP ILLUSTRATOR WINDOWS MACOS
                  <span class="nowrap">MATERIAL
                  UI</span> </p>
              </section>
              <section style="padding: 1.5em 0">
                <h3>Character&#128170;</h3>
                <p class="tags small">FUNNY RESPONSIBLE CONSISTENT CHALLENGING ENTHUSIASTIC CONFIDENT </p>
              </section>
              <section style="padding: 1.5em 0">
                <h3>Likes&#128077;</h3>
                <p class="tags small">HUMOUR
                  HUMOUR <span class="nowrap">HAVING FUN </span> TRAVELLING COOKING EATING <span class="nowrap">SEA AND
                  BEACHES </span> <span class="nowrap">Word “naïve”</span> ​<span class="nowrap">SUPERBOWL
                  COMMERCIALS</span>OSCAR COSMETICS FASHON
                  BIRDS NATURE</p>
              </section>
              <section style="padding: 1.5em 0">
                <h3>Dislikes&#128078;</h3>
                <p class="tags small">SPIDERS<span class="nowrap">OWN BAD HABITS</span> POLITICS VODKA ARROGANCE ENVY
                  VIOLENCE MILK </p>
              </section>
              <section style="padding: 1.5em 0">
                <h3>Wants&#x1f97a;</h3>
                <p class="tags small bulleted"><span class="tag">TO BE FIT AND HEALTHY</span><span class="tag">VISIT NY
                  AGAIN</span><span class="tag">LEARN HOW TO SWIM</span><span class="tag">SPEAK FRENCH
                  FLUENTLY</span><span class="tag">TO BE
                  BRAVE</span><span class="tag">HAVE MY OWN BUSINESS </span><span class="tag">READ A LOT </span></p>
              </section>
              <section style="padding: 1.5em 0">
                <h3>Education</h3>
                <ul class="timeline">
                  <li>
                    <div><em>Every day</em></div>
                    <p class="tags bulleted">
                      <span class="tag"><a href="https://www.w3schools.com/" rel="external">W3Schools</a></span>
                      <span class="tag"><a href="https://css-tricks.com/" rel="external">CSS Tricks</a></span>
                      <span class="tag"><a href="www.udemy.com" rel="external">Udemy</a></span>
                      <span class="tag"><a href="https://egghead.io/" rel="external"><strong>egghead.io</strong></a></span>
                      <span class="tag"><a href="https://theverge.com/" rel="external"><strong>The Verge</strong></a></span>
                      <span class="tag"><a href="https://uncrate.com/" rel="external"><strong>Uncrate</strong></a></span>
                    </p>
                  </li>
                  <li>
                    <div><em>February 2019 &ndash; June 2019</em></div>
                    <div><strong>Front-end Course</strong> at <a href="https://beetroot.academy/en/"
                      rel="external"><strong>Beetroot Academy </strong></a></div>
                  </li>
                  <li>
                    <div><em>October 2018 &ndash; December 2018</em></div>
                    <div><strong>HTML, CSS Course </strong> at <a href="http://infopulse-school.com.ua/"
                      rel="external"><strong>Infopulse </strong></a></div>
                  </li>
                  <li>
                    <div><em>June 2015</em></div>
                    <div><strong>Diploma in International Financial Reporting</strong> </div>
                  </li>
                  <li>
                    <div><em>2010 &ndash; 2011</em></div>
                    <div><strong>French course</strong> at <a href="https://institutfrancais-ukraine.com/"
                      rel="external"><strong>Institut Français Kyiv</strong></a></div>
                  </li>
                  <li>
                    <div><em>2008 &ndash; 2013</em></div>
                    <div><strong>Faculty of Accounting and Audit </strong> at <a href="https://kneu.edu.ua/en/"
                      rel="external"><strong>Kyiv National Economic University named after Vadym Hetman</strong></a></div>
                  </li>
                  <li>
                    <div><em>1<sup>st</sup> September 1998 &ndash; 31<sup>st</sup> May 2008</em></div>
                    <div><strong>Certificate of graduation</strong> at <strong>School-collegium # 36</strong></div>
                  </li>
                </ul>

**Comment by daashkins** [comment]
Thanks
